<a href="https://colab.research.google.com/github/mowhamadrexa/EECS3481Assignments/blob/main/Q3_14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

# Encryption
The first step is to remove the spaces and group the plaintext into 24 pairs
why 24? because the length of the plaintext is 47, si we add 'z' to the end to make it an even number, which is 48. then 48 = 24 * 2

In [11]:
plain = "meet me at the usual place at ten rather than eight o clock"

# let's remove the spaces
plain = plain.replace(' ', '')
plain += "z"
matrix = np.array(list(plain)).reshape(24,2)
matrix

array([['m', 'e'],
       ['e', 't'],
       ['m', 'e'],
       ['a', 't'],
       ['t', 'h'],
       ['e', 'u'],
       ['s', 'u'],
       ['a', 'l'],
       ['p', 'l'],
       ['a', 'c'],
       ['e', 'a'],
       ['t', 't'],
       ['e', 'n'],
       ['r', 'a'],
       ['t', 'h'],
       ['e', 'r'],
       ['t', 'h'],
       ['a', 'n'],
       ['e', 'i'],
       ['g', 'h'],
       ['t', 'o'],
       ['c', 'l'],
       ['o', 'c'],
       ['k', 'z']], dtype='<U1')

Now we convert all the letters to their corresponding number
a = 0, b = 1, c = 2, ... , z = 25

In [26]:
alphabet = list("abcdefghijklmnopqrstuvwxyz")
plain
digitPlain = []
for i in plain:
  digitPlain.append(alphabet.index(i))
matrixDigit = np.array(digitPlain).reshape(24, 2)
matrixDigit

array([[12,  4],
       [ 4, 19],
       [12,  4],
       [ 0, 19],
       [19,  7],
       [ 4, 20],
       [18, 20],
       [ 0, 11],
       [15, 11],
       [ 0,  2],
       [ 4,  0],
       [19, 19],
       [ 4, 13],
       [17,  0],
       [19,  7],
       [ 4, 17],
       [19,  7],
       [ 0, 13],
       [ 4,  8],
       [ 6,  7],
       [19, 14],
       [ 2, 11],
       [14,  2],
       [10, 25]])

The key is:$$Key = \begin{pmatrix} 7 & 3 \\ 2 & 5 \end{pmatrix}$$

In [27]:
key = np.array([[7, 3],[2, 5]])
key

array([[7, 3],
       [2, 5]])

Here is the crucial part. We multiply the Key and each pair, and save the `mod 26` of the result to `cipherDigit`:
$$cipher = Key \cdot  pair \bmod 26$$

$$\begin{pmatrix} 7 & 3 \\ 2 & 5 \end{pmatrix}.\begin{pmatrix} 12 \\ 4 \end{pmatrix}\bmod 26 = \begin{pmatrix} 18 \\ 18 \end{pmatrix}$$

$$\begin{pmatrix} 7 & 3 \\ 2 & 5 \end{pmatrix}.\begin{pmatrix} 4 \\ 19 \end{pmatrix}\bmod 26 = \begin{pmatrix} 7 \\ 25 \end{pmatrix}$$

$$\begin{pmatrix} 7 & 3 \\ 2 & 5 \end{pmatrix}.\begin{pmatrix} 12 \\ 4 \end{pmatrix}\bmod 26 = \begin{pmatrix} 18 \\ 18 \end{pmatrix}$$

$$\vdots$$

$$\begin{pmatrix} 7 & 3 \\ 2 & 5 \end{pmatrix}.\begin{pmatrix} 10 \\ 25 \end{pmatrix}\bmod 26 = \begin{pmatrix} 15 \\ 15 \end{pmatrix}$$

In [40]:
cipherDigit = []
for i in matrixDigit:
  cipherDigit.append((key @ i) % 26)
cipherDigit = np.array(cipherDigit)
cipherDigit

array([[18, 18],
       [ 7, 25],
       [18, 18],
       [ 5, 17],
       [24, 21],
       [10,  4],
       [ 4,  6],
       [ 7,  3],
       [ 8,  7],
       [ 6, 10],
       [ 2,  8],
       [ 8,  3],
       [15, 21],
       [15,  8],
       [24, 21],
       [ 1, 15],
       [24, 21],
       [13, 13],
       [ 0, 22],
       [11, 21],
       [19,  4],
       [21,  7],
       [ 0, 12],
       [15, 15]])

Now we convert all numbers to their corresponding letter: a = 0, b = 1, c = 2, ... , z = 25

In [44]:
cipher = []
for i in cipherDigit.reshape(48):
  cipher.append(alphabet[i])
cipher = "".join(cipher)
cipher

'sshzssfryvkeeghdihgkciidpvpiyvbpyvnnawlvtevhampp'

# The cipher is **"sshzssfryvkeeghdihgkciidpvpiyvbpyvnnawlvtevhampp"**
